### ISSUE TITLE
Error on cache manager

### ISSUE THREAD

**Issue by stijnhau** [hrevert/HtProfileImage#9]
After a instalation of the dev-master on zf 2.3.0

Additionele informatie:
Zend\ServiceManager\Exception\ServiceNotFoundException

Bestand:

```
D:\Dropbox\server\Workspace\True-Life\vendor\zendframework\zendframework\library\Zend\ServiceManager\ServiceManager.php:529
```

Bericht:

```
Zend\ServiceManager\ServiceManager::get was unable to fetch or create an instance for HtImgModule\Service\CacheManager
```

Stack trace:

```
#0 D:\Dropbox\server\Workspace\True-Life\vendor\hrevert\ht-profile-image\src\HtProfileImage\Factory\CacheManagerFactory.php(13): Zend\ServiceManager\ServiceManager->get('HtImgModule\Ser...')
#1 [internal function]: HtProfileImage\Factory\CacheManagerFactory->createService(Object(Zend\ServiceManager\ServiceManager), 'htprofileimages...', 'HtProfileImage\...')
#2 D:\Dropbox\server\Workspace\True-Life\vendor\zendframework\zendframework\library\Zend\ServiceManager\ServiceManager.php(902): call_user_func(Array, Object(Zend\ServiceManager\ServiceManager), 'htprofileimages...', 'HtProfileImage\...')
#3 D:\Dropbox\server\Workspace\True-Life\vendor\zendframework\zendframework\library\Zend\ServiceManager\ServiceManager.php(1032): Zend\ServiceManager\ServiceManager->createServiceViaCallback(Array, 'htprofileimages...', 'HtProfileImage\...')
#4 D:\Dropbox\server\Workspace\True-Life\vendor\zendframework\zendframework\library\Zend\ServiceManager\ServiceManager.php(612): Zend\ServiceManager\ServiceManager->createFromFactory('htprofileimages...', 'HtProfileImage\...')
#5 D:\Dropbox\server\Workspace\True-Life\vendor\zendframework\zendframework\library\Zend\ServiceManager\ServiceManager.php(572): Zend\ServiceManager\ServiceManager->doCreate('HtProfileImage\...', 'htprofileimages...')
#6 D:\Dropbox\server\Workspace\True-Life\vendor\zendframework\zendframework\library\Zend\ServiceManager\ServiceManager.php(504): Zend\ServiceManager\ServiceManager->create(Array)
#7 D:\Dropbox\server\Workspace\True-Life\vendor\hrevert\ht-profile-image\src\HtProfileImage\View\Helper\Factory\ProfileImageFactory.php(20): Zend\ServiceManager\ServiceManager->get('HtProfileImage\...')
#8 [internal function]: HtProfileImage\View\Helper\Factory\ProfileImageFactory->createService(Object(Zend\View\HelperPluginManager), 'htprofileimagev...', 'htProfileImage')
#9 D:\Dropbox\server\Workspace\True-Life\vendor\zendframework\zendframework\library\Zend\ServiceManager\ServiceManager.php(902): call_user_func(Array, Object(Zend\View\HelperPluginManager), 'htprofileimagev...', 'htProfileImage')
#10 D:\Dropbox\server\Workspace\True-Life\vendor\zendframework\zendframework\library\Zend\ServiceManager\AbstractPluginManager.php(245): Zend\ServiceManager\ServiceManager->createServiceViaCallback(Array, 'htprofileimagev...', 'htProfileImage')
#11 D:\Dropbox\server\Workspace\True-Life\vendor\zendframework\zendframework\library\Zend\ServiceManager\AbstractPluginManager.php(205): Zend\ServiceManager\AbstractPluginManager->createServiceViaCallback(Array, 'htprofileimagev...', 'htProfileImage')
#12 D:\Dropbox\server\Workspace\True-Life\vendor\zendframework\zendframework\library\Zend\ServiceManager\ServiceManager.php(612): Zend\ServiceManager\AbstractPluginManager->createFromFactory('htprofileimagev...', 'htProfileImage')
#13 D:\Dropbox\server\Workspace\True-Life\vendor\zendframework\zendframework\library\Zend\ServiceManager\ServiceManager.php(572): Zend\ServiceManager\ServiceManager->doCreate('htProfileImage', 'htprofileimagev...')
#14 D:\Dropbox\server\Workspace\True-Life\vendor\zendframework\zendframework\library\Zend\ServiceManager\ServiceManager.php(504): Zend\ServiceManager\ServiceManager->create(Array)
#15 D:\Dropbox\server\Workspace\True-Life\vendor\zendframework\zendframework\library\Zend\ServiceManager\AbstractPluginManager.php(103): Zend\ServiceManager\ServiceManager->get('htProfileImage', true)
#16 D:\Dropbox\server\Workspace\True-Life\vendor\zendframework\zendframework\library\Zend\View\Renderer\PhpRenderer.php(377): Zend\ServiceManager\AbstractPluginManager->get('htProfileImage', NULL)
#17 D:\Dropbox\server\Workspace\True-Life\vendor\zendframework\zendframework\library\Zend\View\Renderer\PhpRenderer.php(396): Zend\View\Renderer\PhpRenderer->plugin('htProfileImage')
#18 D:\Dropbox\server\Workspace\True-Life\vendor\hrevert\ht-profile-image\view\zfc-user\user\index.phtml(1): Zend\View\Renderer\PhpRenderer->__call('htProfileImage', Array)
#19 D:\Dropbox\server\Workspace\True-Life\vendor\hrevert\ht-profile-image\view\zfc-user\user\index.phtml(1): Zend\View\Renderer\PhpRenderer->htProfileImage(Object(ZfcUser\Entity\User))
#20 D:\Dropbox\server\Workspace\True-Life\vendor\zendframework\zendframework\library\Zend\View\Renderer\PhpRenderer.php(506): include('D:\Dropbox\serv...')
#21 D:\Dropbox\server\Workspace\True-Life\vendor\zendframework\zendframework\library\Zend\View\View.php(205): Zend\View\Renderer\PhpRenderer->render(Object(Zend\View\Model\ViewModel))
```

**Comment by ojhaujjwal** [comment]
Thanks for pointing that out. This module has dependency on `HtImgModule`. So, you need to add `HtImgModule` in `config/application.config.php`. I have updated the installation docs.

**Comment by ojhaujjwal** [comment]
And do not use `dev-master` version of this module. Instead use `2.0.*`!

**Comment by stijnhau** [comment]
Indeed found it out just  after i made the post.
Also wy shouldn't i use dev-master branch?

**Comment by ojhaujjwal** [comment]
Because only the tagged version should be used in production. If you want to contribute, then, clone this repo and start hacking!

**Comment by stijnhau** [comment]
i already forked it so taht's why i use the dev-master version.
With a cvs link to my github page.
